// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxtglaqmuxdpnkqgtagf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dGdsYXFtdXhkcG5rcWd0YWdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MzkyNTksImV4cCI6MjA2MzMxNTI1OX0.1SSk-cvrEnR1WYIMzBBH_9tKGo5GH4h0hGcSC5sGCl8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);